[package]
name = "advent_of_code_2024"
version = "0.1.0"
edition = "2021"

[dependencies]

[[bin]]
name = "day1-1"
path = "day1/part_one.rs"

[[bin]]
name = "day1-2"
path = "day1/part_two.rs"

[[bin]]
name = "day2-1"
path = "day2/part_one.rs"
